name: Cache list for PHP versions from Git tags

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the entire git history

      - name: Get all tags
        id: get_tags
        run: |
          tags=$(git tag -l)

          if [[ -z "$tags" ]]; then
            echo "No tags found!"
            exit 1
          fi

          sorted_tags=$(echo "$tags" | sort -V)
          echo "$sorted_tags" > versions

          versions_json=$(echo "$sorted_tags" | jq -R -s -c 'split("\n")[:-1]')
          echo "versions=$versions_json" >> $GITHUB_OUTPUT

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add versions
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "wip(cache): Update versions file with all tags ($(date +'%Y-%m-%d'))"
            git push
          fi
